import { z } from 'zod';
import type { DocType } from '../types/documents';

const FOOTER = '\n\n— Generated by Alln1 Business (template) — review before use.';

export type TemplateId =
  | 'nda_v1'
  | 'service_agreement_v1'
  | 'contractor_agreement_v1'
  | 'w9_request_letter_v1';

const baseFieldsSchema = z.object({
  partyName: z.string().min(1, 'Party name required'),
  partyAddress: z.string().optional(),
  partyEmail: z.string().email().optional().or(z.literal('')),
  effectiveDate: z.string().optional(),
  jurisdiction: z.string().optional(),
});

const ndaSchema = baseFieldsSchema.extend({
  disclosingParty: z.string().optional(),
  receivingParty: z.string().optional(),
  termMonths: z.string().optional(),
});

const serviceAgreementSchema = baseFieldsSchema.extend({
  projectScope: z.string().optional(),
  paymentTerms: z.string().optional(),
  termLength: z.string().optional(),
});

const contractorAgreementSchema = baseFieldsSchema.extend({
  projectScope: z.string().optional(),
  paymentTerms: z.string().optional(),
  termLength: z.string().optional(),
});

const w9RequestSchema = baseFieldsSchema.extend({
  vendorName: z.string().optional(),
  dueDate: z.string().optional(),
});

export type NdaData = z.infer<typeof ndaSchema>;
export type ServiceAgreementData = z.infer<typeof serviceAgreementSchema>;
export type ContractorAgreementData = z.infer<typeof contractorAgreementSchema>;
export type W9RequestData = z.infer<typeof w9RequestSchema>;
export type TemplateData = NdaData | ServiceAgreementData | ContractorAgreementData | W9RequestData;

export type TemplateDef<T = TemplateData> = {
  id: TemplateId;
  name: string;
  description: string;
  doc_type: DocType;
  category: 'legal' | 'vendor' | 'customer' | 'tax' | 'other';
  schema: z.ZodSchema<T>;
  renderTemplate: (data: T, business: { name?: string; address?: string }) => string;
  aiPrompt?: (data: T, business: { name?: string; address?: string }) => string;
};

function renderNda(data: NdaData, business: { name?: string; address?: string }): string {
  const disclosing = data.disclosingParty || business.name || '[Disclosing Party]';
  const receiving = data.receivingParty || data.partyName;
  const term = data.termMonths ? `${data.termMonths} months` : '24 months';

  return `NON-DISCLOSURE AGREEMENT

This Non-Disclosure Agreement ("Agreement") is entered into as of ${data.effectiveDate || '[Effective Date]'}.

PARTIES:
- Disclosing Party: ${disclosing}
  ${business.address || '[Address]'}

- Receiving Party: ${receiving}
  ${data.partyAddress || '[Address]'}
  ${data.partyEmail ? `Email: ${data.partyEmail}` : ''}

PURPOSE:
The Disclosing Party will share confidential information with the Receiving Party for business purposes. The Receiving Party agrees to keep such information confidential.

CONFIDENTIALITY:
The Receiving Party agrees not to disclose, use, or reproduce any confidential information except as necessary for the stated purpose. Confidential information includes business plans, financial data, customer lists, and technical information.

TERM:
This Agreement remains in effect for ${term} from the Effective Date. Obligations of confidentiality survive termination.

GOVERNING LAW:
This Agreement is governed by the laws of ${data.jurisdiction || 'the State of [Jurisdiction]'}.${FOOTER}`;
}

function renderServiceAgreement(
  data: ServiceAgreementData,
  business: { name?: string; address?: string }
): string {
  const client = data.partyName;
  const scope = data.projectScope || '[Describe scope of services]';
  const payment = data.paymentTerms || '[Describe payment terms]';
  const term = data.termLength || '[Duration]';

  return `SERVICE AGREEMENT

This Service Agreement ("Agreement") is entered into as of ${data.effectiveDate || '[Effective Date]'}.

SERVICE PROVIDER: ${business.name || '[Your Business]'}
Address: ${business.address || '[Address]'}

CLIENT: ${client}
Address: ${data.partyAddress || '[Address]'}
${data.partyEmail ? `Email: ${data.partyEmail}` : ''}

SCOPE OF SERVICES:
${scope}

PAYMENT TERMS:
${payment}

TERM:
${term}

GOVERNING LAW:
This Agreement is governed by the laws of ${data.jurisdiction || 'the State of [Jurisdiction]'}.${FOOTER}`;
}

function renderContractorAgreement(
  data: ContractorAgreementData,
  business: { name?: string; address?: string }
): string {
  const contractor = data.partyName;
  const scope = data.projectScope || '[Describe project scope]';
  const payment = data.paymentTerms || '[Describe payment terms]';
  const term = data.termLength || '[Duration]';

  return `INDEPENDENT CONTRACTOR AGREEMENT

This Independent Contractor Agreement ("Agreement") is entered into as of ${data.effectiveDate || '[Effective Date]'}.

COMPANY: ${business.name || '[Your Business]'}
Address: ${business.address || '[Address]'}

CONTRACTOR: ${contractor}
Address: ${data.partyAddress || '[Address]'}
${data.partyEmail ? `Email: ${data.partyEmail}` : ''}

SCOPE OF WORK:
${scope}

COMPENSATION:
${payment}

TERM:
${term}

INDEPENDENT CONTRACTOR:
Contractor is an independent contractor, not an employee. Contractor is responsible for their own taxes and insurance.

GOVERNING LAW:
This Agreement is governed by the laws of ${data.jurisdiction || 'the State of [Jurisdiction]'}.${FOOTER}`;
}

function renderW9Request(data: W9RequestData, business: { name?: string; address?: string }): string {
  const vendor = data.vendorName || data.partyName;
  const due = data.dueDate || '[Date]';

  return `W-9 REQUEST LETTER

Date: ${data.effectiveDate || '[Date]'}

To: ${vendor}
${data.partyAddress ? `Address: ${data.partyAddress}` : ''}
${data.partyEmail ? `Email: ${data.partyEmail}` : ''}

From: ${business.name || '[Your Business]'}
${business.address ? `Address: ${business.address}` : ''}

Subject: Request for Completed Form W-9

Dear ${vendor},

Please complete and return IRS Form W-9 (Request for Taxpayer Identification Number and Certification) by ${due}.

We require your W-9 for our records to comply with federal tax reporting requirements for payments we make to you.

Please provide:
- Completed and signed Form W-9
- Legal name as it appears on your tax return
- Taxpayer Identification Number (TIN) or Social Security Number (SSN)

You may download Form W-9 from the IRS website at https://www.irs.gov/forms-pubs/about-form-w-9

Thank you for your prompt attention to this matter.

Sincerely,
${business.name || '[Your Business]'}` + FOOTER;
}

export const templates: TemplateDef[] = [
  {
    id: 'nda_v1',
    name: 'Non-Disclosure Agreement',
    description: 'Protect confidential business information shared with partners or contractors.',
    doc_type: 'nda',
    category: 'legal',
    schema: ndaSchema,
    renderTemplate: renderNda,
    aiPrompt: (d, b) =>
      `Generate a professional NDA between Disclosing Party "${b.name || 'Company'}" and Receiving Party "${d.partyName}". Effective date: ${d.effectiveDate || 'TBD'}. Include standard confidentiality, term, and governing law sections. Keep it concise and professional.`,
  },
  {
    id: 'service_agreement_v1',
    name: 'Service Agreement',
    description: 'Define scope, payment, and terms for client services.',
    doc_type: 'agreement',
    category: 'customer',
    schema: serviceAgreementSchema,
    renderTemplate: renderServiceAgreement,
    aiPrompt: (d, b) =>
      `Generate a professional Service Agreement. Service provider: "${b.name || 'Company'}". Client: "${d.partyName}". Scope: ${d.projectScope || 'General services'}. Payment: ${d.paymentTerms || 'TBD'}. Effective: ${d.effectiveDate || 'TBD'}. Include term, governing law.`,
  },
  {
    id: 'contractor_agreement_v1',
    name: 'Contractor Agreement',
    description: 'Engage independent contractors with clear scope and payment terms.',
    doc_type: 'contract',
    category: 'vendor',
    schema: contractorAgreementSchema,
    renderTemplate: renderContractorAgreement,
    aiPrompt: (d, b) =>
      `Generate an Independent Contractor Agreement. Company: "${b.name || 'Company'}". Contractor: "${d.partyName}". Scope: ${d.projectScope || 'Consulting services'}. Payment: ${d.paymentTerms || 'TBD'}. Include independent contractor status, term, governing law.`,
  },
  {
    id: 'w9_request_letter_v1',
    name: 'W-9 Request Letter',
    description: 'Request W-9 from vendors for tax compliance.',
    doc_type: 'other',
    category: 'tax',
    schema: w9RequestSchema,
    renderTemplate: renderW9Request,
    aiPrompt: (d, b) =>
      `Generate a brief W-9 request letter from "${b.name || 'Company'}" to vendor "${d.vendorName || d.partyName}". Due date: ${d.dueDate || 'within 10 days'}. Professional and concise.`,
  },
];

export function getTemplate(id: TemplateId): TemplateDef | undefined {
  return templates.find((t) => t.id === id);
}
